import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { hashKeyName } from "../crypto/envelope.js";
import { unlockDek } from "../crypto/keyring.js";
import { many, one, type Command } from "../cli/command.js";
import { locateCatalogs } from "../loader/locate.js";
import { readEntries, readWraps, type CatalogEntry } from "../loader/read.js";
import { openDatabaseSync, type Database } from "../sqlite/open.js";
import { resolveUnlock } from "./unlock.js";

export type Sensitivity = "low" | "medium" | "high" | "critical";

/** Unset means medium: a key nobody classified must not end up in a bundle. */
export const DEFAULT_SENSITIVITY: Sensitivity = "medium";

const LEVELS: ReadonlySet<string> = new Set([
  "low",
  "medium",
  "high",
  "critical",
]);

export function isSensitivity(value: string): value is Sensitivity {
  return LEVELS.has(value);
}

export function readSensitivity(
  db: Database,
  dek: Uint8Array,
  key: string,
): Sensitivity {
  const row = db
    .prepare<{ sensitivity: string | null }>(
      "SELECT sensitivity FROM keys WHERE key_hash = $hash",
    )
    .get({ hash: hashKeyName(dek, key) });
  const value = row?.sensitivity ?? null;
  return value !== null && isSensitivity(value) ? value : DEFAULT_SENSITIVITY;
}

/** Prefixes the surrounding ecosystem already treats as client-visible. */
const PUBLIC_PREFIXES = ["PUBLIC_", "VITE_", "NEXT_PUBLIC_"];

function isPublicByName(key: string): boolean {
  return PUBLIC_PREFIXES.some((prefix) => key.startsWith(prefix));
}

function asIdentifier(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function renderModule(
  chosen: readonly CatalogEntry[],
  generatedAt: string,
): string {
  const lines = [
    "// Generated by envs. Do not edit.",
    `// ${generatedAt}`,
    "//",
    "// Every value here is baked into whatever imports this file. Only keys",
    "// classified low reach it; see envs build.",
    "",
  ];
  for (const entry of chosen) {
    // Provenance in the output answers "where did this come from" later.
    lines.push(`/** from ${entry.alias} (${entry.path}) */`);
    lines.push(
      `export const ${asIdentifier(entry.key)} = ${JSON.stringify(entry.value)};`,
    );
  }
  lines.push("");
  lines.push("export const ENV = {");
  for (const entry of chosen) {
    lines.push(`  ${asIdentifier(entry.key)},`);
  }
  lines.push("} as const;");
  lines.push("");
  lines.push("export type EnvKey = keyof typeof ENV;");
  lines.push("");
  return lines.join("\n");
}

export const buildCommand: Command = {
  name: "build",
  describe:
    "write chosen values into a module, for targets that cannot read files",
  usage: "envs build --out <path> [--expose K1,K2]",
  options: [
    {
      name: "out",
      placeholder: "<path>",
      describe: "where to write the module",
    },
    {
      name: "expose",
      placeholder: "<K1,K2>",
      describe: "keys to include; repeatable",
      repeat: true,
    },
    {
      name: "public",
      boolean: true,
      describe: `also include keys named ${PUBLIC_PREFIXES.join(", ")}`,
    },
    {
      name: "allow-sensitive",
      boolean: true,
      describe: "bake a key that is not classified low (it cannot be recalled)",
    },
    {
      name: "recovery-code",
      placeholder: "<code|->",
      describe: "unlock with a recovery code; - reads it from stdin",
    },
  ],

  run({ ui, args, env, cwd }) {
    const out = one(args, "out");
    if (out === undefined) {
      ui.error("no output path", "envs build --out src/generated/env.ts");
      return 2;
    }

    const located = locateCatalogs({ cwd, env });
    if (!existsSync(located.project)) {
      ui.error("no catalog here", located.project);
      return 1;
    }
    const unlock = resolveUnlock(one(args, "recovery-code"), env);
    if (typeof unlock === "string") {
      ui.error(unlock);
      return 2;
    }

    const asked = new Set(
      many(args, "expose")
        .flatMap((value) => value.split(","))
        .map((key) => key.trim())
        .filter((key) => key !== ""),
    );
    const wantPublic = args.flags.has("public");
    if (asked.size === 0 && !wantPublic) {
      // Defaulting to everything is the easy way to put a secret in a bundle,
      // and a deployed bundle cannot be recalled.
      ui.error(
        "nothing selected, so nothing was written",
        "--expose K1,K2 or --public",
      );
      return 2;
    }

    const db = openDatabaseSync(located.project, { readOnly: true });
    try {
      const dek = unlockDek(readWraps(db), unlock);
      const entries = readEntries(db, { unlock });

      const seen = new Map<string, CatalogEntry>();
      for (const entry of entries) {
        if (!seen.has(entry.key)) seen.set(entry.key, entry);
      }

      const wanted = [...seen.values()].filter(
        (entry) =>
          asked.has(entry.key) || (wantPublic && isPublicByName(entry.key)),
      );

      const missing = [...asked].filter((key) => !seen.has(key));
      if (missing.length > 0) {
        ui.error(`no value for ${missing.join(", ")}`, "nothing was written");
        return 1;
      }

      const refused: string[] = [];
      const chosen: CatalogEntry[] = [];
      for (const entry of wanted) {
        const level = readSensitivity(db, dek, entry.key);
        if (level === "low" || args.flags.has("allow-sensitive")) {
          chosen.push(entry);
          continue;
        }
        refused.push(`${entry.key} (${level})`);
      }

      if (refused.length > 0) {
        ui.error("these are not classified low", refused.join(", "));
        ui.info(
          "envs set <KEY> <value> --sensitivity low",
          "or --allow-sensitive to bake them anyway",
        );
        return 1;
      }
      if (chosen.length === 0) {
        ui.error("nothing to write", "no selected key survived the check");
        return 1;
      }

      const path = resolve(cwd, out);
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, renderModule(chosen, new Date().toISOString()));

      ui.success(`wrote ${out}`, `${chosen.length} values`);
      ui.warn(
        "these are now in whatever imports that file",
        chosen.map((entry) => entry.key).join(", "),
      );
      return 0;
    } catch (error) {
      ui.error((error as Error).message);
      return 1;
    } finally {
      db.close();
    }
  },
};
