import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { authorised } from "../src/commands/serve.js";
import { isSensitivity } from "../src/commands/build.js";
import { Ui, type Stream } from "../src/cli/ui.js";
import { COMMANDS, dispatch, PLANNED } from "../src/commands/index.js";

class Capture implements Stream {
  text = "";
  isTTY = false;
  write(chunk: string): boolean {
    this.text += chunk;
    return true;
  }
}

const KEK = Buffer.from(new Uint8Array(32).fill(61)).toString("base64");
const TOKEN = "a-token-of-at-least-16";

let dir: string;
let out: Capture;
let err: Capture;

async function run(
  argv: readonly string[],
  env: Record<string, string> = { ENVS_KEK: KEK },
): Promise<number> {
  out = new Capture();
  err = new Capture();
  return dispatch(argv, {
    ui: new Ui({ stdout: out, stderr: err, color: false, env: {} }),
    env,
    cwd: dir,
  });
}

beforeEach(async () => {
  dir = join(mkdtempSync(join(tmpdir(), "envs-bs-")), "project");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "package.json"), "{}\n");
  await run(["init", "--recovery-codes", "1"]);
  writeFileSync(
    join(dir, ".env"),
    "PUBLIC_API=https://api.example\nAPI_SECRET=s3cr3t\nPLAIN=ok\n",
  );
  await run(["load", ".env"]);
});

afterEach(() => rmSync(join(dir, ".."), { recursive: true, force: true }));

describe("everything the design named is built", () => {
  it("has nothing left planned", () => {
    expect(PLANNED).toEqual([]);
  });

  it("has build and serve", () => {
    const names = COMMANDS.map((command) => command.name);
    expect(names).toContain("build");
    expect(names).toContain("serve");
  });
});

describe("build refuses before it writes", () => {
  const outPath = () => join(dir, "src", "env.ts");

  it("writes nothing when nothing was selected", async () => {
    expect(await run(["build", "--out", "src/env.ts"])).toBe(2);
    expect(existsSync(outPath())).toBe(false);
    expect(err.text).toContain("--expose");
  });

  it("refuses a key that is not classified low", async () => {
    expect(
      await run(["build", "--out", "src/env.ts", "--expose", "API_SECRET"]),
    ).toBe(1);
    expect(existsSync(outPath())).toBe(false);
    expect(err.text).toContain("not classified low");
    expect(err.text).toContain("(medium)");
  });

  it("refuses a PUBLIC_ name too, until it is classified", async () => {
    expect(await run(["build", "--out", "src/env.ts", "--public"])).toBe(1);
    expect(existsSync(outPath())).toBe(false);
  });

  it("writes once the key is classified low", async () => {
    await run([
      "set",
      "PUBLIC_API",
      "https://api.example",
      "--sensitivity",
      "low",
    ]);
    expect(await run(["build", "--out", "src/env.ts", "--public"])).toBe(0);

    const text = readFileSync(outPath(), "utf8");
    expect(text).toContain('export const PUBLIC_API = "https://api.example"');
    expect(text).toContain("Generated by envs");
    // Provenance travels with the value.
    expect(text).toContain("from env");
    // And nothing unclassified came along.
    expect(text).not.toContain("s3cr3t");
  });

  it("bakes a sensitive key only when told to, and says what it did", async () => {
    expect(
      await run([
        "build",
        "--out",
        "src/env.ts",
        "--expose",
        "API_SECRET",
        "--allow-sensitive",
      ]),
    ).toBe(0);
    expect(readFileSync(outPath(), "utf8")).toContain("s3cr3t");
    expect(err.text).toContain("now in whatever imports that file");
  });

  it("refuses a key the catalog does not have", async () => {
    expect(
      await run(["build", "--out", "src/env.ts", "--expose", "NOPE"]),
    ).toBe(1);
    expect(err.text).toContain("no value for NOPE");
    expect(existsSync(outPath())).toBe(false);
  });

  it("takes a level only from the four it knows", async () => {
    expect(isSensitivity("low")).toBe(true);
    expect(isSensitivity("public")).toBe(false);
    expect(await run(["set", "PLAIN", "ok", "--sensitivity", "public"])).toBe(
      2,
    );
  });
});

describe("serve", () => {
  it("insists on a token long enough to be one", async () => {
    expect(await run(["serve"], { ENVS_KEK: KEK })).toBe(2);
    expect(err.text).toContain("ENVS_SERVE_TOKEN");
    expect(await run(["serve"], { ENVS_SERVE_TOKEN: "short" })).toBe(2);
  });

  it("refuses a port that is not one", async () => {
    expect(
      await run(["serve", "--port", "99999"], { ENVS_SERVE_TOKEN: TOKEN }),
    ).toBe(2);
  });

  it("accepts the right bearer token and nothing else", () => {
    expect(authorised(`Bearer ${TOKEN}`, TOKEN)).toBe(true);
    expect(authorised(`Bearer ${TOKEN}x`, TOKEN)).toBe(false);
    expect(authorised(TOKEN, TOKEN)).toBe(false);
    expect(authorised(undefined, TOKEN)).toBe(false);
    expect(authorised("Bearer ", TOKEN)).toBe(false);
  });

  it("hands over the sealed catalog, which a client still cannot read", async () => {
    const port = 7400 + Math.floor(Math.random() * 500);
    const server = run(["serve", "--port", String(port), "--once"], {
      ENVS_KEK: KEK,
      ENVS_SERVE_TOKEN: TOKEN,
    });
    // The listener is up by the time a request round-trips; --once stops it.
    await new Promise((r) => setTimeout(r, 150));

    const unauthorised = await fetch(`http://127.0.0.1:${port}/v1/catalog`);
    expect(unauthorised.status).toBe(401);

    const response = await fetch(`http://127.0.0.1:${port}/v1/catalog`, {
      headers: { authorization: `Bearer ${TOKEN}` },
    });
    expect(response.status).toBe(200);
    const bytes = new Uint8Array(await response.arrayBuffer());
    expect(bytes.length).toBeGreaterThan(1000);
    // A sqlite file, and no value legible in it.
    expect(new TextDecoder().decode(bytes.subarray(0, 16))).toContain("SQLite");
    expect(
      new TextDecoder("utf8", { fatal: false }).decode(bytes),
    ).not.toContain("s3cr3t");

    expect(await server).toBe(0);
  });
});
